name: Build and Package

on:
  push:
    branches: [master, master-2, main]
  pull_request:
    branches: [master, master-2, main]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build paul1893 FlexToolTweak .tipa
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install Homebrew
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh')"

      - name: Set up Theos
        run: |
          export THEOS=~/theos
          [ -d "$THEOS" ] && (cd "$THEOS" && git pull --recurse-submodules) || git clone --recursive https://github.com/theos/theos.git "$THEOS"
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          echo "$THEOS/bin" >> $GITHUB_PATH
          git clone --depth=1 https://github.com/theos/headers.git /tmp/theos-headers
          mkdir -p ~/theos/vendor/include
          cp -R /tmp/theos-headers/* ~/theos/vendor/include/
          echo "THEOS_PACKAGE_SCHEME=rootless" >> $GITHUB_ENV
          echo "THEOS_USE_LIBHOOKER=0" >> $GITHUB_ENV
          echo "TWEAK_USE_ELLEKIT=0" >> $GITHUB_ENV

      - name: Install make
        run: brew install make

      - name: Setup Theos environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Make FlexToolTweak package
        run: ./make.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlexToolTweak.tipa
          path: ./packages/FlexToolTweak.tipa

      - name: Get FlexToolTweak artifact
        uses: actions/download-artifact@v4
        with:
          name: FlexToolTweak.tipa

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          release_name: Build ${{ github.run_number }}
          draft: false
          prerelease: false
